#!/bin/bash

# Script para deployar Banca Victoria en Railway
# Uso: ./deploy-railway.sh

echo "=================================="
echo "BANCA VICTORIA - DEPLOY RAILWAY"
echo "=================================="
echo ""
echo "PASOS MANUALES:"
echo ""
echo "1. Ve a https://railway.app y crea una cuenta (usa tu GitHub)"
echo ""
echo "2. Crea un nuevo proyecto:"
echo "   - Click en 'New Project'"
echo "   - Selecciona 'Empty Project'"
echo ""
echo "3. Agrega una base de datos MySQL:"
echo "   - Click en 'New' → 'Database' → 'Add MySQL'"
echo "   - Espera a que se cree (toma 1-2 minutos)"
echo ""
echo "4. Agrega el servicio de la app:"
echo "   - Click en 'New' → 'GitHub Repo'"
echo "   - Sube este proyecto a GitHub primero"
echo "   - Selecciona el repositorio"
echo ""
echo "5. Configura las variables de entorno:"
echo "   - Ve a tu servicio → 'Variables'"
echo "   - Click en 'New Variable'"
echo "   - Agrega: DATABASE_URL (Railway la genera automaticamente con la DB)"
echo "   - Agrega: NODE_ENV=production"
echo "   - Agrega: PORT=3000"
echo ""
echo "6. Deploy:"
echo "   - Railway detecta el Dockerfile y hace deploy automatico"
echo "   - Espera 2-3 minutos"
echo "   - Click en el link que te da Railway"
echo ""
echo "7. Inicializa la base de datos:"
echo "   - Ve a tu servicio → 'Deployments'"
echo "   - Click en los tres puntos del deploy actual"
echo "   - Selecciona 'Shell'"
echo "   - Ejecuta: npx tsx db/seed.ts"
echo ""
echo "=================================="
echo "Para soporte, contacta al administrador"
echo "=================================="
